
file:
  save-path:  /Users/jun/temp/note

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/note
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

  web:
    resources:
      static-locations: file:/Users/jun/Documents/test/build
server:
  port: 8000